CREATE TABLE "SYSTEM"."PLAYERDB" 
   ("ID" NUMBER(25,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20), 
	"DP" NUMBER(15,0) NOT NULL ENABLE, 
	 CONSTRAINT "PLAYERDB_PK" PRIMARY KEY ("ID") ENABLE
   );

CREATE TABLE "SYSTEM"."PGame" 
   ("Round" NUMBER(25,0) NOT NULL ENABLE);
