INSERT INTO CUSTOMERS(ID, FIRSTNAME, AGE, ADDRESS, SALARY)
VALUES (1, 'LINI', 56, 'NAGA', 374678);

INSERT INTO CUSTOMERS(ID, FIRSTNAME, AGE, ADDRESS, SALARY)
VALUES (2, 'REGIO', 77, 'DAVAO', 423432);

SAVEPOINT sav1;

UPDATE CUSTOMERS
SET SALARY = SALARY + 1000;
ROLLBACK TO sav1;


UPDATE CUSTOMERS
SET SALARY = SALARY + 1000
WHERE ID = 1;


UPDATE CUSTOMERS
SET SALARY = SALARY + 1000
WHERE ID = 2;

COMMIT;